name: Deploy Node.js App to Dokku grit-web02.grit.ucsb.edu

on:
  push:
    branches:
      - main  

jobs:
  deploy:
    runs-on: self-hosted
    steps:
    - name: Check out code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install Dependencies
      run: npm install

    - name: Build
      run: CI=false npm run build

    - name: Set up SSH
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan -p 22 grit-web02.grit.ucsb.edu >> ~/.ssh/known_hosts

    - name: Deploy to Dokku
      run: |
        git config --global user.email "actions@github.com"
        git config --global user.name "GitHub Actions"
        git remote add dokku dokku@grit-web02.grit.ucsb.edu:chc-snippets || git remote set-url dokku dokku@grit-web02.grit.ucsb.edu:chc-snippets
        git push dokku +main
      working-directory: ./
